In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([2])
b = tf.constant([3])

In [3]:
c = tf.add(a, b)

In [4]:
session = tf.Session()

In [5]:
result = session.run(c)
print(result)

[5]


In [6]:
session.close()

In [7]:
with tf.Session() as session:
    result = session.run(c)
    print(result)

[5]


In [8]:
Scalar = tf.constant([2])
Vector = tf.constant([5, 6, 2])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant([ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ])
with tf.Session() as session:
    result = session.run(Scalar)
    print 'Scalar: %s' % result
    result = session.run(Vector)
    print 'Vector: %s' % result
    result = session.run(Matrix)
    print 'Matrix: %s' % result
    result = session.run(Tensor)
    print 'Tensor: %s' % result

Scalar: [2]
Vector: [5 6 2]
Matrix: [[1 2 3]
 [2 3 4]
 [3 4 5]]
Tensor: [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


In [9]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

first_operation = tf.add(Matrix_one, Matrix_two)
second_operation = Matrix_one + Matrix_two

with tf.Session() as session:
    result = session.run(first_operation)
    print result
    result = session.run(second_operation)
    print result

[[3 4 5]
 [4 5 6]
 [5 6 7]]
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [10]:
Matrix_one = tf.constant([[2,3],[3,4]])
Matrix_two = tf.constant([[2,3],[3,4]])

first_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.Session() as session:
    result = session.run(first_operation)
    print result

[[13 18]
 [18 25]]


In [11]:
state = tf.Variable(0)

In [12]:
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

In [13]:
init_op = tf.global_variables_initializer()

In [14]:
with tf.Session() as session:
    session.run(init_op)
    print(session.run(state))
    for _ in range(3):
        session.run(update)
        print(session.run(state))

0
1
2
3


In [15]:
a = tf.placeholder(tf.float32)

In [16]:
b = a * 2

In [21]:
with tf.Session() as session:
    result = session.run(b, feed_dict={a:3.5})
    print result

7.0


In [25]:
dictionary = {a: [ [[1,2,3],[4,5,6],[7,8,9],[10,11,12]] , [[13,14,15],[16,17,18],[19,20,21],[22,23,24]] ]}

with tf.Session() as session:
    result = session.run(b, feed_dict=dictionary)
    print result

[[[  2.   4.   6.]
  [  8.  10.  12.]
  [ 14.  16.  18.]
  [ 20.  22.  24.]]

 [[ 26.  28.  30.]
  [ 32.  34.  36.]
  [ 38.  40.  42.]
  [ 44.  46.  48.]]]


In [27]:
a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a,b)
d = tf.subtract(a,b)

with tf.Session() as sess:
    result = sess.run(c)
    print result
    result = sess.run(d)
    print result

[7]
[3]
