In [8]:
%matplotlib inline
import tensorflow as tf

In [10]:
a = tf.constant([5])
b = tf.constant([2])

In [19]:
c = a + b
print c
with tf.Session() as sess:
    result = sess.run(c)
    print result

Tensor("add_5:0", shape=(1,), dtype=int32)
[7]


In [20]:
d = tf.multiply(a, b)
print d
with tf.Session() as sess:
    result = sess.run(d)
    print result

Tensor("Mul_2:0", shape=(1,), dtype=int32)
[10]


In [21]:
matrixA = tf.constant([[2,3],[3,4]])
matrixB = tf.constant([[2,3],[3,4]])

In [23]:
e = matrixA * matrixB
f = tf.matmul(matrixA, matrixB)
with tf.Session() as sess:
    result = sess.run(e)
    print result
    
    result = sess.run(f)
    print result

[[ 4  9]
 [ 9 16]]
[[13 18]
 [18 25]]


In [32]:
a = tf.constant(1000)
b = tf.Variable(0)
init_op = tf.global_variables_initializer()

In [33]:
update = tf.assign(b, a)
with tf.Session() as sess:
    sess.run(init_op)
    sess.run(update)
    print sess.run(b)

1000


In [57]:
a = tf.Variable(1)
b = tf.Variable(1)
temp = tf.Variable(0)
c = tf.add(a, b)

update1 = tf.assign(temp, c)
update2 = tf.assign(a, b)
update3 = tf.assign(b, temp)

init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op)
    print sess.run(a)
    print sess.run(b)
    for i in range(10):
        print sess.run(c)
        sess.run(update1)
        sess.run(update2)
        sess.run(update3)

1
1
2
3
5
8
13
21
34
55
89
144


In [61]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

c = 2*a - b

dictionary = {a:[2,2,2], b:[3,4,5]}

with tf.Session() as sess:
    print sess.run(c, feed_dict = dictionary)

[ 1.  0. -1.]


In [62]:
a = tf.constant(5.)
b = tf.constant(2.)

c = tf.pow(b, a)

with tf.Session() as sess:
    print sess.run(c)

32.0
