In [6]:
import numpy as np
import tensorflow as tf
from __future__ import print_function
sess = tf.Session()

In [11]:
LSTM_CELL_SIZE = 4

lstm_cell = tf.contrib.rnn.BasicLSTMCell(LSTM_CELL_SIZE, state_is_tuple=True)
state = (tf.zeros([2, LSTM_CELL_SIZE]),) * 2
state

(<tf.Tensor 'zeros_6:0' shape=(2, 4) dtype=float32>,
 <tf.Tensor 'zeros_6:0' shape=(2, 4) dtype=float32>)

In [12]:
sample_input = tf.constant([[1,2,3,4,3,2],[3,2,2,2,2,2]], dtype=tf.float32)
print (sess.run(sample_input))

[[ 1.  2.  3.  4.  3.  2.]
 [ 3.  2.  2.  2.  2.  2.]]


In [13]:
with tf.variable_scope("LSTM_sample1"):
    output, state_new = lstm_cell(sample_input, state)
sess.run(tf.global_variables_initializer())
print (sess.run(state_new))

LSTMStateTuple(c=array([[ 0.07862474, -0.95861286,  0.91418695,  0.28611967],
       [ 0.32825243, -0.61465466,  0.41978425,  0.46286783]], dtype=float32), h=array([[ 0.03773763, -0.21297911,  0.08687916,  0.26692858],
       [ 0.19750065, -0.23976135,  0.1510618 ,  0.34430578]], dtype=float32))


In [14]:
print (sess.run(output))

[[ 0.03773763 -0.21297911  0.08687916  0.26692858]
 [ 0.19750065 -0.23976135  0.1510618   0.34430578]]


In [15]:
sess = tf.Session()

In [16]:
LSTM_CELL_SIZE = 4
input_dim = 6
num_layers = 2

In [17]:
cells = []
for _ in range(num_layers):
    cell = tf.contrib.rnn.LSTMCell(LSTM_CELL_SIZE)
    cells.append(cell)
stacked_lstm = tf.contrib.rnn.MultiRNNCell(cells)

In [18]:
data = tf.placeholder(tf.float32, [None, None, input_dim])
output, state = tf.nn.dynamic_rnn(cell, data, dtype=tf.float32)

In [19]:
sample_input = [[[1,2,3,4,3,2], [1,2,1,1,1,2],[1,2,2,2,2,2]],[[1,2,3,4,3,2],[3,2,2,1,1,2],[0,0,0,0,3,2]]]
sample_input

[[[1, 2, 3, 4, 3, 2], [1, 2, 1, 1, 1, 2], [1, 2, 2, 2, 2, 2]],
 [[1, 2, 3, 4, 3, 2], [3, 2, 2, 1, 1, 2], [0, 0, 0, 0, 3, 2]]]

In [20]:
sess.run(tf.global_variables_initializer())
sess.run(output, feed_dict={data: sample_input})

array([[[ 0.00468854, -0.08007617, -0.44080892,  0.24137746],
        [ 0.04408274, -0.13529131, -0.68578136,  0.27758288],
        [ 0.06447446, -0.22934648, -0.69591981,  0.25026113]],

       [[ 0.00468854, -0.08007617, -0.44080892,  0.24137746],
        [ 0.01985058, -0.01485206, -0.58932877,  0.35972762],
        [ 0.03456735, -0.2809256 , -0.4066945 ,  0.2006546 ]]], dtype=float32)